// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dragOver': string;
  'icon': string;
  'options': string;
  'over': string;
}
export const cssExports: CssExports;
export default cssExports;
